"""
awnode Persistent Service Install
=====================================

Turns `awnode start` into a real always-on host service so the browser
extension (AitherConnect) and portal always have a live local endpoint:
Turns `aithernode start` into a real always-on host service so the browser
extension (Awconnect) and portal always have a live local endpoint:

- Windows: per-user Scheduled Task (runs at logon, restarts on failure)
- Linux:   systemd *user* unit (`~/.config/systemd/user/awnode.service`); a
           *system* unit (`/etc/systemd/system/awnode.service`) as root or under
           WSL, where no user systemd instance exists (the awnix fleet distro)
- macOS:   launchd agent (`~/Library/LaunchAgents/com.aitherium.awnode.plist`)

All operations are idempotent; only the Linux system-unit case needs root (sudo -n).
"""

import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional

SERVICE_NAME = "awnode"
TASK_NAME = "awnode Local Gateway"
SYSTEMD_UNIT = "awnode.service"
LAUNCHD_LABEL = "com.aitherium.awnode"


def _node_command(port: int, host: str) -> List[str]:
    """Resolve the command that starts the node, preferring the console script."""
    exe = shutil.which("awnode")
    if exe:
        return [exe, "start", "--host", host, "--port", str(port)]
    return [sys.executable, "-m", "awnode", "start", "--host", host, "--port", str(port)]


def _run(cmd: List[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True)


# ── Windows (Scheduled Task) ────────────────────────────────────────

# A GUI-subsystem launcher: WScript.Shell.Run(cmd, 0, True) starts the payload
# hidden and waits, so the exit code still propagates. wscript.exe is itself
# GUI-subsystem, so Task Scheduler allocates NO console for it.
#
# This package cannot import awdk's copy (separate distribution, installed
# independently), so the shim is duplicated here deliberately rather than by
# accident. Keep the two in step.
_RUN_HIDDEN_VBS = (
    "' Launch a console payload with no visible window.\r\n"
    "' Generated by awnode.service_install — do not edit.\r\n"
    "Set sh = CreateObject(\"WScript.Shell\")\r\n"
    "args = \"\"\r\n"
    "For i = 0 To WScript.Arguments.Count - 1\r\n"
    "  args = args & \"\"\"\" & WScript.Arguments(i) & \"\"\" \"\r\n"
    "Next\r\n"
    "WScript.Quit sh.Run(args, 0, True)\r\n"
)


def _win_install(port: int, host: str) -> str:
    cmd = _node_command(port, host)
    # schtasks /TR takes one command string; quote the executable path
    tr = " ".join(f'"{c}"' if " " in c else c for c in cmd)

    # An ONLOGON task launching a console program opens a console ON THE DESKTOP
    # that TAKES FOCUS for as long as the program runs — and the node server runs
    # indefinitely. A customer who joins a node would get a permanent window
    # sitting on their machine eating keystrokes. Route it through the shim; a
    # wrapper .cmd carries the (possibly long) command line so /TR stays short.
    home = Path.home() / ".aither" / "awnode"
    home.mkdir(parents=True, exist_ok=True)
    shim = home / "run-hidden.vbs"
    shim.write_text(_RUN_HIDDEN_VBS, encoding="utf-8")
    wrapper = home / "awnode-start.cmd"
    wrapper.write_text(f'@echo off\r\n{tr}\r\n', encoding="utf-8")

    r = _run([
        "schtasks", "/Create", "/F",
        "/TN", TASK_NAME,
        "/TR", f'wscript.exe //B //Nologo "{shim}" "{wrapper}"',
        "/SC", "ONLOGON",
        "/RL", "LIMITED",
    ])
    if r.returncode != 0:
        raise RuntimeError(f"schtasks create failed: {r.stderr.strip() or r.stdout.strip()}")
    _run(["schtasks", "/Run", "/TN", TASK_NAME])
    return f"installed Windows scheduled task '{TASK_NAME}' (runs at logon; started now)"


def _win_uninstall() -> str:
    _run(["schtasks", "/End", "/TN", TASK_NAME])
    r = _run(["schtasks", "/Delete", "/F", "/TN", TASK_NAME])
    if r.returncode != 0:
        raise RuntimeError(f"schtasks delete failed: {r.stderr.strip() or r.stdout.strip()}")
    return f"removed scheduled task '{TASK_NAME}'"


def _win_status() -> str:
    r = _run(["schtasks", "/Query", "/TN", TASK_NAME, "/FO", "LIST"])
    if r.returncode != 0:
        return "not installed"
    return r.stdout.strip()


def _win_start() -> str:
    r = _run(["schtasks", "/Run", "/TN", TASK_NAME])
    if r.returncode != 0:
        raise RuntimeError(f"schtasks run failed: {r.stderr.strip() or r.stdout.strip()}")
    return "started"


def _win_stop() -> str:
    r = _run(["schtasks", "/End", "/TN", TASK_NAME])
    if r.returncode != 0:
        raise RuntimeError(f"schtasks end failed: {r.stderr.strip() or r.stdout.strip()}")
    return "stopped"


# ── Linux (systemd: user unit, or a system unit as root / under WSL) ─────
#
# A USER unit needs a user systemd instance, which exists only while the user has a
# login session (or lingering). Under WSL -- the awnix fleet distro among them -- and on
# a root-run server there is no such session: `systemctl --user` fails with "Failed to
# connect to bus" and the node never starts. So as root, or under WSL, the node is a
# SYSTEM unit in /etc/systemd/system (running as the invoking user when that is not
# root), wanted by multi-user.target. AWNODE_SYSTEMD_SCOPE=user|system pins it.

SCOPE_ENV = "AWNODE_SYSTEMD_SCOPE"
_WSL_MARKER = Path("/proc/sys/fs/binfmt_misc/WSLInterop")


def _is_root() -> bool:
    return hasattr(os, "geteuid") and os.geteuid() == 0


def _systemd_scope() -> str:
    """``"system"`` as root or under WSL, else ``"user"`` (env AWNODE_SYSTEMD_SCOPE wins)."""
    pinned = (os.environ.get(SCOPE_ENV) or "").strip().lower()
    if pinned in ("user", "system"):
        return pinned
    # A user unit installed before the system-scope rule keeps being managed where it is:
    # otherwise status says "not installed" and uninstall leaves it enabled.
    if not _is_root() and (Path.home() / ".config" / "systemd" / "user" / SYSTEMD_UNIT).exists():
        return "user"
    if _is_root() or _WSL_MARKER.exists():
        return "system"
    return "user"


def _systemd_unit_path(scope: Optional[str] = None) -> Path:
    if (scope or _systemd_scope()) == "system":
        return Path("/etc/systemd/system") / SYSTEMD_UNIT
    return Path.home() / ".config" / "systemd" / "user" / SYSTEMD_UNIT


def _systemctl(scope: str, *args: str) -> List[str]:
    """argv for systemctl in this scope (``sudo -n`` for a system unit when not root)."""
    if scope == "user":
        return ["systemctl", "--user", *args]
    return (["systemctl"] if _is_root() else ["sudo", "-n", "systemctl"]) + list(args)


def _render_unit(exec_start: str, scope: str, user: Optional[str] = None) -> str:
    """The unit text. A system unit runs as ``user`` (when given) and is wanted by
    multi-user.target; a user unit by default.target."""
    run_as = f"User={user}\n" if (scope == "system" and user and user != "root") else ""
    wanted = "multi-user.target" if scope == "system" else "default.target"
    return f"""[Unit]
Description=awnode local gateway (browser proxy + inference)
After=network-online.target
Wants=network-online.target

[Service]
ExecStart={exec_start}
{run_as}Restart=on-failure
RestartSec=5
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy={wanted}
"""


def _write_unit(path: Path, text: str, scope: str) -> None:
    if scope == "user" or _is_root():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        return
    # Bytes, not text=True: the unit must arrive with LF endings exactly as rendered.
    r = subprocess.run(["sudo", "-n", "tee", str(path)], input=text.encode("utf-8"),
                       capture_output=True)
    if r.returncode != 0:
        err = r.stderr.decode("utf-8", "replace").strip()
        raise RuntimeError(
            f"writing {path} needs root (sudo -n failed: {err}); "
            f"re-run as root or set {SCOPE_ENV}=user")


def _linux_install(port: int, host: str) -> str:
    scope = _systemd_scope()
    cmd = _node_command(port, host)
    user = None if _is_root() else (os.environ.get("USER") or os.environ.get("LOGNAME"))
    path = _systemd_unit_path(scope)
    _write_unit(path, _render_unit(" ".join(cmd), scope, user), scope)
    for args in (["daemon-reload"], ["enable", "--now", SYSTEMD_UNIT]):
        r = _run(_systemctl(scope, *args))
        if r.returncode != 0:
            raise RuntimeError(f"{' '.join(_systemctl(scope, *args))} failed: {r.stderr.strip()}")
    return f"installed systemd {scope} unit {path} (enabled + started)"


def _linux_uninstall() -> str:
    scope = _systemd_scope()
    _run(_systemctl(scope, "disable", "--now", SYSTEMD_UNIT))
    path = _systemd_unit_path(scope)
    if path.exists():
        if scope == "user" or _is_root():
            path.unlink()
        else:
            _run(["sudo", "-n", "rm", "-f", str(path)])
    _run(_systemctl(scope, "daemon-reload"))
    return f"removed {path}"


def _linux_status() -> str:
    r = _run(_systemctl(_systemd_scope(), "status", SYSTEMD_UNIT, "--no-pager"))
    return r.stdout.strip() or "not installed"


def _linux_start() -> str:
    r = _run(_systemctl(_systemd_scope(), "start", SYSTEMD_UNIT))
    if r.returncode != 0:
        raise RuntimeError(f"systemctl start failed: {r.stderr.strip()}")
    return "started"


def _linux_stop() -> str:
    r = _run(_systemctl(_systemd_scope(), "stop", SYSTEMD_UNIT))
    if r.returncode != 0:
        raise RuntimeError(f"systemctl stop failed: {r.stderr.strip()}")
    return "stopped"


# ── macOS (launchd agent) ───────────────────────────────────────────


def _launchd_plist_path() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{LAUNCHD_LABEL}.plist"


def _macos_install(port: int, host: str) -> str:
    cmd = _node_command(port, host)
    args_xml = "\n".join(f"        <string>{c}</string>" for c in cmd)
    plist = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{LAUNCHD_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
{args_xml}
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
</dict>
</plist>
"""
    path = _launchd_plist_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(plist, encoding="utf-8")
    _run(["launchctl", "unload", str(path)])
    r = _run(["launchctl", "load", str(path)])
    if r.returncode != 0:
        raise RuntimeError(f"launchctl load failed: {r.stderr.strip()}")
    return f"installed launchd agent {path} (loaded)"


def _macos_uninstall() -> str:
    path = _launchd_plist_path()
    _run(["launchctl", "unload", str(path)])
    if path.exists():
        path.unlink()
    return f"removed {path}"


def _macos_status() -> str:
    r = _run(["launchctl", "list", LAUNCHD_LABEL])
    if r.returncode != 0:
        return "not installed"
    return r.stdout.strip()


def _macos_start() -> str:
    r = _run(["launchctl", "load", str(_launchd_plist_path())])
    if r.returncode != 0:
        raise RuntimeError(f"launchctl load failed: {r.stderr.strip()}")
    return "started"


def _macos_stop() -> str:
    r = _run(["launchctl", "unload", str(_launchd_plist_path())])
    if r.returncode != 0:
        raise RuntimeError(f"launchctl unload failed: {r.stderr.strip()}")
    return "stopped"


# ── Dispatch ────────────────────────────────────────────────────────


def _platform() -> str:
    sysname = platform.system().lower()
    if sysname.startswith("win"):
        return "windows"
    if sysname == "darwin":
        return "macos"
    return "linux"


def service_action(action: str, port: int = 8090, host: Optional[str] = None) -> str:
    """Perform a service lifecycle action. Returns a human-readable result."""
    # Default the persistent service to loopback: its job is serving the
    # LOCAL browser. LAN exposure is an explicit opt-in via --service-host.
    host = host or os.environ.get("AITHERNODE_SERVICE_HOST", "127.0.0.1")
    plat = _platform()
    table = {
        "windows": {
            "install": lambda: _win_install(port, host),
            "uninstall": _win_uninstall,
            "status": _win_status,
            "start": _win_start,
            "stop": _win_stop,
        },
        "linux": {
            "install": lambda: _linux_install(port, host),
            "uninstall": _linux_uninstall,
            "status": _linux_status,
            "start": _linux_start,
            "stop": _linux_stop,
        },
        "macos": {
            "install": lambda: _macos_install(port, host),
            "uninstall": _macos_uninstall,
            "status": _macos_status,
            "start": _macos_start,
            "stop": _macos_stop,
        },
    }
    handler = table[plat].get(action)
    if not handler:
        raise ValueError(f"unknown service action '{action}'")
    return handler()
